### ISSUE TITLE
Can this be used as a documentation tool?

### ISSUE THREAD

**Issue by andrerpena** [istarkov/react-components-markdown#1]
Hi, thanks for this. This seems cool.
I can see how to use it within a "React context", but what if I want to use this as a "documentation tool", is that possible? I mean, a feed the tool with `.md` documents and it generates some sort of HTML documents? I'm just wondering.
Thank you anyway.

**Comment by istarkov** [comment]
We use it at work as a part of our sandbox-documentation engine. It's just a React component which you can use with additional tooling.

**Comment by andrerpena** [comment]
Thanks!
